from multi_type_search.search.termination_criteria.termination_criteria import TerminationCriteria
from multi_type_search.search.termination_criteria.types.wall_clock_time import WallClockTimeTermination
