data_files:
        #orig_data_file: 'data/full/entailmentbank/task_1/test.jsonl'
        #orig_data_file: 'data/full/entailmentbank/task_1/test_tfidf_distractor_goals.jsonl'
        #orig_data_file: 'data/full/entailmentbank/task_2/test_tfidf_distractor_goals.jsonl'
        orig_data_file: 'data/full/morals/moral100.json'
        #orig_data_file: 'data/full/entailmentbank/task_2/test.jsonl'

create_shallow_graphs:
  depth: -1
  min_depth: -1
  max_depth: -1
  keep_extra_premises: true

create_premise_masked_graphs:
  premises_to_mask: 0

search:

  max_steps: 10
  torch_devices: ['cuda:0']

  all_one_premise: false
  mix_distractors: true
  shuffle_premises: true

  step_selector:
    type: 'vector_space_step_selector'
    arguments:
      iter_size: 1
      deductive_nms_threshold: 0.995
      use_nms: false
      similarity_metric: 'cosine'
      weight_by_rep_score: true
      model:
        constructor_type: "search_model"
        type: "node_embedder"
        arguments:
                model_name: "raw_gpt3"
                batch_size: 1


  step_type:
    - type: 'deductive_step_type'
      arguments:
        step_model:
          constructor_type: 'search_model'
          type: 'step_model'
          arguments:
            model_name: 't5_large_pps_eb_step'
            max_output_length: 128
            num_return_sequences: 5
            batch_size: 1

  step_validator:
    - type: 'consanguinity_threshold_step_validator'
      arguments:
        threshold: 3
        compare_subindex: false

  generation_validator:

    - type: 'deduplication_generation_validator'
      arguments:
        threshold: 0.9
        check_arguments: true
        check_matching_generation_type: true
        check_other_generations: true
        normalize_values: true
        comparison:
          constructor_type: 'comparison_metric'
          type: 'exact_comparison'
          arguments:

    - type: 'contrastive_filter_validator'
      arguments:
        threshold: 0.5
        embedder:
          constructor_type: "search_model"
          type: "node_embedder"
          arguments:
            model_name: "raw_gpt3"
            batch_size: 1


graph_goal_comparisons:
  torch_devices: ['cuda:0']
  use_normalized_values: true
  allowed_graphkeytypes: ['DEDUCTIVE']

  comparison_metric:
        constructor_type: 'comparison_metric'
        type: 'entailment_comparison'
        arguments:
          entailment_method: 'group_to_target'
          entailment_model:
            constructor_type: 'search_model'
            type: 'entailment_model'
            arguments:
              model_name: 'trained_models/wanli_entailment_model'
              batch_size: 4

graph_missing_premise_comparisons:
  torch_devices: [ 'cuda:0' ]
  use_normalized_values: true
  allowed_graphkeytypes: [ 'ABDUCTIVE' ]

  comparison_metric:
        constructor_type: 'comparison_metric'
        type: 'rouge_entailment_hm_comparison'
        arguments:
          rouge_comparison:
                  constructor_type: 'comparison_metric'
                  type: 'rouge_comparison'
                  arguments:
                          rouge_types:
                                - 'rouge1'
          entailment_comparison:
            constructor_type: 'comparison_metric'
            type: 'entailment_comparison'
            arguments:
              entailment_method: 'mutual'
              entailment_model:
                constructor_type: 'search_model'
                type: 'entailment_model'
                arguments:
                  model_name: 'wanli_entailment_model'
                  batch_size: 4

find_proofs:
  proof_types:
    - score_name: 'goal_score'
      threshold: 0.81
      graph_key_types: [ 'DEDUCTIVE' ]

search_report_args:
  basic_stats: true
  duplicate_gen_stats: false
  expansion_stats: true
  premise_usage_stats: true
  self_bleu_stats: false
  self_bleu_weights:
    - 0.33
    - 0.33
    - 0.33
  self_rouge_stats: false
  proof_stats: true
  print_report: true
  device: 'cuda:0'
