from pathlib import Path

SEARCH_FOLDER = Path(__file__).parent.parent
SEARCH_DATA_FOLDER = SEARCH_FOLDER / 'data'
SEARCH_OUTPUT_FOLDER = SEARCH_FOLDER / 'output'
SEARCH_CONFIGS_FOLDER = SEARCH_FOLDER / 'configs'
SEARCH_SCRIPTS_FOLDER = SEARCH_FOLDER / 'scripts'

ROOT_FOLDER: Path = SEARCH_FOLDER.parent.resolve()
DATA_FOLDER = ENTAILMENT_BANK_FOLDER = ROOT_FOLDER / 'data'
ENTAILMENT_BANK_FOLDER = ROOT_FOLDER / 'data/full/entailmentbank'
MORALS_DATA_FOLDER = ROOT_FOLDER / 'data/full/morals'
TRAINED_MODELS_FOLDER = ROOT_FOLDER / 'trained_models'
GPT_3_FOLDER = ROOT_FOLDER / 'gpt3'

PROMPTS_FOLDER = GPT_3_FOLDER / 'prompts'
OUTPUTS_FOLDER = GPT_3_FOLDER / 'outputs'
EXPORTS_FOLDER = OUTPUTS_FOLDER / 'exports'
